services:
  - type: web
    name: codecure-api
    env: python
    pythonVersion: 3.11
    plan: free
    buildCommand: "pip install -r requirements.txt && python train_toxicity_model.py"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8080"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
    autoDeploy: true
